# Mastering Pandas read_csv() with Examples â€“ A Tutorial by CodesWithPankaj.com

Introduction:

Pandas, a powerful data manipulation library in Python, has become an essential tool for data scientists and analysts. One of its key functions is `read_csv()`, which allows users to read data from CSV (Comma-Separated Values) files into a Pandas DataFrame. In this tutorial, brought to you by CodesWithPankaj.com, we will explore the intricacies of `read_csv()` with clear examples to help you harness its full potential.

Understanding read_csv():

`read_csv()` is a versatile function that offers various parameters to handle diverse scenarios when reading CSV files. Whether your dataset has a specific delimiter, contains missing values, or requires custom column names, Pandas provides options to accommodate these situations.

##  Importing a CSV file using the read_csv() function

In [1]:
# Importing the Pandas library
import pandas as pd

# Specify the file path or URL of the CSV file
file_path = 'DataSet/p4n_emp.csv'

# Use the read_csv() function to read the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
print(df.head())

                    name  age     sex  \
0         Aaron, Dayan M   38    Male
1       Aaron, Freddie L   52    Male
2        Aaron, Tyrone M   44    Male
3        Abazenab, Kokeb   42  Female
4  Abbott, Christopher D   32    Male

                                       ethnic.origin  \
0  Black or African American (Not Hispanic or Lat...
1  Black or African American (Not Hispanic or Lat...
2  Black or African American (Not Hispanic or Lat...
3  Black or African American (Not Hispanic or Lat...
4                     White (Not Hispanic or Latino)

                            job.title  \
0                    ATL311 Team Lead
1  Environmental Service Worker I (D)
2       Watershed Crew Supervisor (D)
3         Benefits Representative, Sr
4     Recreation Operations Assistant

                                organization  annual.salary
0                      EXE Executive Offices       45999.99
1             DPW Department of Public Works       26700.10
2     DWM Department of Watershed Management       46575.01
3           DHR Department of Human Reources       42866.89
4  PRC Parks, Recreation, & Cultural Affairs       28035.05

## Setting a column as the index

In [1]:
# Importing the Pandas library
import pandas as pd

# Specify the file path of the CSV file
file_path = 'DataSet/p4n_emp.csv'

# Use the read_csv() function to read the CSV file into a DataFrame and set "name" as the index
df = pd.read_csv(file_path, index_col='name')

# Display the first few rows of the DataFrame
print(df.head())

                       age     sex  \
name
Aaron, Dayan M          38    Male
Aaron, Freddie L        52    Male
Aaron, Tyrone M         44    Male
Abazenab, Kokeb         42  Female
Abbott, Christopher D   32    Male

                                                           ethnic.origin  \
name
Aaron, Dayan M         Black or African American (Not Hispanic or Lat...
Aaron, Freddie L       Black or African American (Not Hispanic or Lat...
Aaron, Tyrone M        Black or African American (Not Hispanic or Lat...
Abazenab, Kokeb        Black or African American (Not Hispanic or Lat...
Abbott, Christopher D                     White (Not Hispanic or Latino)

                                                job.title  \
name
Aaron, Dayan M                           ATL311 Team Lead
Aaron, Freddie L       Environmental Service Worker I (D)
Aaron, Tyrone M             Watershed Crew Supervisor (D)
Abazenab, Kokeb               Benefits Representative, Sr
Abbott, Christopher D     Recreation Operations Assistant

                                                    organization  \
name
Aaron, Dayan M                             EXE Executive Offices
Aaron, Freddie L                  DPW Department of Public Works
Aaron, Tyrone M           DWM Department of Watershed Management
Abazenab, Kokeb                 DHR Department of Human Reources
Abbott, Christopher D  PRC Parks, Recreation, & Cultural Affairs

                       annual.salary
name
Aaron, Dayan M              45999.99
Aaron, Freddie L            26700.10
Aaron, Tyrone M             46575.01
Abazenab, Kokeb             42866.89
Abbott, Christopher D       28035.05

## Selecting specific columns to read into memory

In [3]:
# Importing the Pandas library
import pandas as pd

# Specify the file path of the CSV file
file_path = 'DataSet/p4n_emp.csv'

# Specify the columns you want to select
selected_columns = ['name', 'age', 'sex']

# Use the read_csv() function to read only the specified columns into a DataFrame
df = pd.read_csv(file_path, usecols=selected_columns)

# Display the first few rows of the DataFrame
print(df.head())

                    name  age     sex
0         Aaron, Dayan M   38    Male
1       Aaron, Freddie L   52    Male
2        Aaron, Tyrone M   44    Male
3        Abazenab, Kokeb   42  Female
4  Abbott, Christopher D   32    Male

### DataFrame Methods:

1. **head(n=5)**:
   - Displays the first n rows of the DataFrame.
   ```python
   df.head(10)  # Display the first 10 rows
   ```

2. **tail(n=5)**:
   - Displays the last n rows of the DataFrame.
   ```python
   df.tail(8)  # Display the last 8 rows
   ```

3. **info()**:
   - Provides a concise summary of the DataFrame, including data types and missing values.
   ```python
   df.info()
   ```

4. **describe()**:
   - Generates descriptive statistics of the DataFrame's numerical columns.
   ```python
   df.describe()
   ```

5. **shape**:
   - Returns a tuple representing the dimensions (rows, columns) of the DataFrame.
   ```python
   print(df.shape)
   ```

6. **columns**:
   - Returns an Index object containing the column labels.
   ```python
   print(df.columns)
   ```

7. **unique()**:
   - Returns an array of unique values in a specified column.
   ```python
   unique_values = df['column_name'].unique()
   ```

8. **value_counts()**:
   - Returns a Series containing counts of unique values in a specified column.
   ```python
   value_counts = df['column_name'].value_counts()
   ```

9. **sort_values()**:
   - Sorts the DataFrame by specified column(s).
   ```python
   df_sorted = df.sort_values(by='column_name')
   ```

10. **groupby()**:
    - Groups the DataFrame by specified column(s) for further aggregation.
    ```python
    grouped_data = df.groupby('column_name').mean()
    ```

### DataFrame Attributes:

1. **index**:
   - Returns the index (row labels) of the DataFrame.
   ```python
   print(df.index)
   ```

2. **values**:
   - Returns a two-dimensional array of the DataFrame's values.
   ```python
   print(df.values)
   ```

3. **dtypes**:
   - Returns a Series with the data type of each column.
   ```python
   print(df.dtypes)
   ```

4. **shape**:
   - Returns a tuple representing the dimensions (rows, columns) of the DataFrame.
   ```python
   print(df.shape)
   ```

5. **columns**:
   - Returns an Index object containing the column labels.
   ```python
   print(df.columns)
   ```

6. **size**:
   - Returns the number of elements in the DataFrame (rows * columns).
   ```python
   print(df.size)
   ```

### Exporting the DataFrame to a CSV File

In [4]:
# Assuming df is your DataFrame
import pandas as pd

# Specify the file path for the CSV output
output_file_path = 'output_data.csv'

# Use the to_csv() method to export the DataFrame to a CSV file
df.to_csv(output_file_path, index=False)

# Display a message indicating the successful export
print(f"DataFrame exported to {output_file_path}")

DataFrame exported to output_data.csv

In [5]:
# Assuming df is your DataFrame
import pandas as pd

# Specify the file path for the CSV input
file_path = 'DataSet/p4n_emp.csv'

# Load the dataset into a DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
print("Original DataFrame:")
print(df.head())

# Filtering: Selecting employees aged 30 or younger
young_employees = df[df['age'] <= 30]

# Display the first few rows of the filtered DataFrame
print("\nYoung Employees:")
print(young_employees.head())

# Grouping: Calculate the average salary by job title
average_salary_by_job = df.groupby('job.title')['annual.salary'].mean().reset_index()

# Display the average salary by job title
print("\nAverage Salary by Job Title:")
print(average_salary_by_job)

# Summary Statistics: Displaying overall summary statistics of the dataset
summary_statistics = df.describe(include='all')

# Display the summary statistics
print("\nSummary Statistics:")
print(summary_statistics)

# Export the filtered DataFrame to a new CSV file
output_filtered_path = 'DataSet/young_employees.csv'
young_employees.to_csv(output_filtered_path, index=False)
print(f"\nFiltered DataFrame exported to {output_filtered_path}")

Original DataFrame:
                    name  age     sex  \
0         Aaron, Dayan M   38    Male
1       Aaron, Freddie L   52    Male
2        Aaron, Tyrone M   44    Male
3        Abazenab, Kokeb   42  Female
4  Abbott, Christopher D   32    Male

                                       ethnic.origin  \
0  Black or African American (Not Hispanic or Lat...
1  Black or African American (Not Hispanic or Lat...
2  Black or African American (Not Hispanic or Lat...
3  Black or African American (Not Hispanic or Lat...
4                     White (Not Hispanic or Latino)

                            job.title  \
0                    ATL311 Team Lead
1  Environmental Service Worker I (D)
2       Watershed Crew Supervisor (D)
3         Benefits Representative, Sr
4     Recreation Operations Assistant

                                organization  annual.salary
0                      EXE Executive Offices       45999.99
1             DPW Department of Public Works       26700.10
2     DWM Department of Watershed Management       46575.01
3           DHR Department of Human Reources       42866.89
4  PRC Parks, Recreation, & Cultural Affairs       28035.05

Young Employees:
                       name  age     sex  \
7      Abdul-Hakeem, Ayesha   28  Female
10    Abernathy, Christiana   21  Female
23           Adams, Ashli A   24  Female
28  Adams, Kelonda Centorya   28  Female
31         Adams, Matthew D   28    Male

                                        ethnic.origin  \
7   Black or African American (Not Hispanic or Lat...
10  Black or African American (Not Hispanic or Lat...
23  Black or African American (Not Hispanic or Lat...
28  Black or African American (Not Hispanic or Lat...
31                     White (Not Hispanic or Latino)

                             job.title  \
7   Police Officer (E) (F) (O) (B) (S)
10                              Intern
23     Recreation Operations Assistant
28  Environmental Service Worker I (D)
31                     Urban Planner I

                                 organization  annual.salary
7               APD Atlanta Police Department       39327.60
10             DPW Department of Public Works       33238.40
23  PRC Parks, Recreation, & Cultural Affairs       25800.01
28             DPW Department of Public Works       25461.01
31       PCD Planning & Community Development       41651.67

Average Salary by Job Title:
                           job.title  annual.salary
0        911 Communications Director  105400.010000
1                   911 Operator (D)   34465.807143
2       ATL 311 Call Center Director  118400.010000
3     ATL 311 Call Center Supervisor   55817.652000
4        ATL 311 Call Center Trainer   55000.000000
..                               ...            ...
765            Watershed Trainee (D)   30223.148000
766                    Web Developer   56261.300000
767                       Welder (D)   42360.330000
768  YouthBuild Construction Manager   54873.100000
769             Zoning Inspector, Sr   45207.010000

[770 rows x 2 columns]

Summary Statistics:
                   name          age   sex  \
count              8246  8246.000000  8246
unique             8242          NaN     2
top     Jones, Sharon R          NaN  Male
freq                  2          NaN  5461
mean                NaN    43.186636   NaN
std                 NaN    11.236170   NaN
min                 NaN    19.000000   NaN
25%                 NaN    34.000000   NaN
50%                 NaN    44.000000   NaN
75%                 NaN    52.000000   NaN
max                 NaN    89.000000   NaN

                                            ethnic.origin  \
count                                                8246
unique                                                  7
top     Black or African American (Not Hispanic or Lat...
freq                                                 6304
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

                                 job.title                   organization  \
count                                 8246                           8246
unique                                 770                             22
top     Police Officer (E) (F) (O) (B) (S)  APD Atlanta Police Department
freq                                  1226                           2349
mean                                   NaN                            NaN
std                                    NaN                            NaN
min                                    NaN                            NaN
25%                                    NaN                            NaN
50%                                    NaN                            NaN
75%                                    NaN                            NaN
max                                    NaN                            NaN

        annual.salary
count     8246.000000
unique            NaN
top               NaN
freq              NaN
mean     49040.302659
std      20042.032049
min      20800.000000
25%      36916.860000
50%      43983.430000
75%      55279.300000
max     240697.600000

Filtered DataFrame exported to DataSet/young_employees.csv

### Conclusion:

The `read_csv()` function in Pandas is a versatile tool that enables seamless data import from CSV files. In this tutorial, we've explored various scenarios, including basic usage, handling custom delimiters, managing missing values, and specifying custom column names. Armed with this knowledge, you'll be better equipped to tackle diverse datasets in your data science endeavors.

Visit CodesWithPankaj.com for more in-depth tutorials and coding insights to enhance your Python and Pandas skills. Happy coding!